/**
 * Action types
 */
const types = {
    SET_APOLLO_CLIENT: "SET_APOLLO_CLIENT",
    SET_LOGGED_USER: "SET_LOGGED_USER",
    SET_TOKEN: "SET_TOKEN",
    SET_ORDERS_PRINT: "SET_ORDERS_PRINT",
    SET_SELECTED_PRODUCT: "SET_SELECTED_PRODUCT",
    SET_NOT_SELECTED_PRODUCT: "SET_NOT_SELECTED_PRODUCT",
    SET_CLEAR_SELECTED_PRODUCT: "SET_CLEAR_SELECTED_PRODUCT",
};

export { types };
